### ISSUE TITLE
Implement resetting password functionality (via email)

### ISSUE THREAD

**Issue by KhweziNtsaluba** [COS301-SE-2024/WhatsOn-UP#105]
- [ ] Create `forgot password` link in login page
- [ ] Implement functionality to send email to user - with the entered email
- [ ] Sent email must have a link to the form mentioned below[^button-example]
- [ ] Take user to form that will allow password to be reset[^form-info]
   - Example in footnotes [^form-example]

[^button-example]: [emailed reset password button](https://github.com/COS301-SE-2024/WhatsOn-UP/assets/162153448/bb46e50f-98ca-4846-9054-df7bbb82f689)
[^form-info]: Create a (static) page where the user is redirected to where a form the new password is entered and sent as form data to the API.
[^form-example]: [Form to reset password](https://github.com/COS301-SE-2024/WhatsOn-UP/assets/162153448/877e5c14-5959-447c-a6b3-6871eea9db8a)

**Comment by zdanise** [comment]
require an redirection link back to the reset page ...don't know how to do that
