### ISSUE TITLE
No way to save events

### ISSUE THREAD

**Issue by KhweziNtsaluba** [COS301-SE-2024/WhatsOn-UP#244]
There is currently no way to actually save events in the frontend

**Comment by zdanise** [comment]
@KhweziNtsaluba done with this, however the addition and removal of saved events I used provider I thought that constantly calling the api would cause a major delay. I wanted to make the official update to the database when the user logs out or leaves the app? when do you think is should do this or we must just call the api every time the user saves or unsave?
